# Generated by Django 4.1 on 2023-05-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.CharField(blank=True, max_length=255, null=True)),
                ("likes", models.CharField(blank=True, max_length=255, null=True)),
                ("time", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "posts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like_list", models.TextField(blank=True, null=True)),
                ("post_list", models.TextField(blank=True, null=True)),
                ("time_list", models.TextField(blank=True, null=True)),
                ("keyword", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "search",
                "managed": False,
            },
        ),
    ]
